universe = vanilla
executable = /home/rbaba/tauspin-ss/MakeNtuple/run_condor.sh
arguments = Z /home/rbaba/tauspin-ss/MakeNtuple/inputs/Z_chunk_000
output = /home/rbaba/tauspin-ss/MakeNtuple/logs/Z_000.$(ClusterId).$(ProcId).out
error = /home/rbaba/tauspin-ss/MakeNtuple/logs/Z_000.$(ClusterId).$(ProcId).err
log = /home/rbaba/tauspin-ss/MakeNtuple/logs/Z_$(ClusterId).log
request_cpus = 1
request_memory = 4GB
getenv = True
queue 1
