universe = vanilla
executable = /home/rbaba/tauspin-ss/MakeNtuple/run_condor.sh
arguments = Z /home/rbaba/tauspin-ss/MakeNtuple/snapshots/fixed-partial-v3-20260730-2100/inputs/Z_chunk_$(chunk).txt fixed-partial-v3-20260730-2100
output = /home/rbaba/tauspin-ss/MakeNtuple/snapshots/fixed-partial-v3-20260730-2100/logs/Z_$(chunk).$(ClusterId).$(ProcId).out
error = /home/rbaba/tauspin-ss/MakeNtuple/snapshots/fixed-partial-v3-20260730-2100/logs/Z_$(chunk).$(ClusterId).$(ProcId).err
log = /home/rbaba/tauspin-ss/MakeNtuple/snapshots/fixed-partial-v3-20260730-2100/logs/Z_$(ClusterId).log
request_cpus = 1
request_memory = 5GB
getenv = True

queue chunk from (
000
001
002
003
004
005
006
007
008
009
010
011
012
013
014
015
016
017
018
019
020
021
022
023
024
025
026
027
028
029
030
031
032
033
034
035
036
037
038
039
040
041
042
043
044
045
046
047
048
)
